import { InspectionItemMaster } from "./types";

export const INSPECTION_ITEMS: InspectionItemMaster[] = [
  { id: "A-1", section: "A. 書類提出等", label: "監督署提出（着工時）", checkpoints: ["特定元方開始"] },
  { id: "A-2", section: "A. 書類提出等", label: "監督署提出（機械等設置届）", checkpoints: ["足場(高さ10mかつ設置期間60日以上)", "型枠支保工"] },
  { id: "B-1", section: "B. 現場運営管理", label: "施工体系図", checkpoints: ["記入状況"] },
  { id: "B-2", section: "B. 現場運営管理", label: "災防協・新規入場", checkpoints: ["災防協記録", "新規入場記録"] },
  { id: "B-3", section: "B. 現場運営管理", label: "作業指示", checkpoints: ["指示書交付", "日報"] },
  { id: "C-1", section: "C. 掲示等", label: "掲示物", checkpoints: ["工事名看板", "三連看板", "安全広場掲示板"] },
  { id: "C-2", section: "C. 掲示等", label: "作業主任者の選任", checkpoints: ["氏名表示(正･副)"] },
  { id: "D-1", section: "D. 整理整頓", label: "安全通路確保", checkpoints: ["場内全般", "足場上・建物内", "高さ1.8m確保", "足元段差"] },
  { id: "D-2", section: "D. 整理整頓", label: "片付け状況", checkpoints: ["不要材の処理", "足場上", "現場周辺"] },
  { id: "D-3", section: "D. 整理整頓", label: "整頓状況", checkpoints: ["資材置き場", "パイプ類", "建設廃棄物"] },
  { id: "D-4", section: "D. 整理整頓", label: "場内地盤", checkpoints: ["デコボコ", "水溜り", "入口鋼板敷状況"] },
  { id: "D-5", section: "D. 整理整頓", label: "清掃、整備", checkpoints: ["事務所", "休憩所", "便所・手洗", "灰皿・消火器"] },
  { id: "E-1", section: "E. 公衆災害防止", label: "周辺の災害、第三者災害の防止", checkpoints: ["仮囲い､ｹﾞｰﾄ", "架空線"] },
  { id: "F-1", section: "F. 墜落災害防止", label: "安全帯使用、親綱等の設置", checkpoints: ["安全帯使用状況", "安全帯取付設備"] },
  { id: "F-2", section: "F. 墜落災害防止", label: "外部足場の設置状況", checkpoints: ["躯体との隙間", "手すり設置", "渡り通路設置"] },
  { id: "F-3", section: "F. 墜落災害防止", label: "内部足場の設置状況", checkpoints: ["昇降設備", "手すり設置"] },
  { id: "F-4", section: "F. 墜落災害防止", label: "開口部、床端部の状況", checkpoints: ["手すり設置", "開口部の明示", "危険等の明示"] },
  { id: "F-5", section: "F. 墜落災害防止", label: "関係者以外の立入禁止", checkpoints: ["型枠作業", "立入禁止表示"] },
  { id: "F-6", section: "F. 墜落災害防止", label: "脚立、梯子の使用状況", checkpoints: ["6尺超の有無"] },
  { id: "G-1", section: "G. 飛来", label: "昇降出入口上部の養生", checkpoints: ["入口前片付け"] },
  { id: "G-2", section: "G. 飛来", label: "取込用ステージの養生", checkpoints: ["ゲート設置"] },
  { id: "G-3", section: "G. 飛来", label: "仮置き材料の飛散・落下防止", checkpoints: ["固定,固縛"] },
  { id: "H-1", section: "H. 建設機械災害防止", label: "機械作業計画書の発行・作業確認", checkpoints: ["計画書の発行", "安全通路指示", "立入禁止措置", "ｺﾝｸﾘｰﾄ打設9項目点検表"] },
  { id: "I-1", section: "I. 電気等", label: "仮設電気配線の点検整備", checkpoints: ["配線状況", "地上配線養生"] },
  { id: "I-2", section: "I. 電気等", label: "仮設電気の管理（分電盤など）", checkpoints: ["取扱責任者", "仮設電気点検表", "アース"] },
  { id: "J-1", section: "J. 環境衛生", label: "作業環境の整備状況", checkpoints: ["照明、換気", "熱中症対策"] },
  { id: "J-2", section: "J. 環境衛生", label: "建設廃棄物の管理状況", checkpoints: ["委託契約書", "保管場所掲示"] },
];
